export const analysisCopy = {
  en: {
    eyebrow: "Research agent",
    title: "Build cited company intelligence",
    description: "Download the latest 10-K, extract its business sections, verify claims, and prepare both languages.",
    start: "Run agent analysis",
    retry: "Retry analysis",
    pending: "Submitting…",
    remaining: "daily analyses remaining",
    failed: "Analysis failed",
    limit: "Daily allowance used",
    reset: "Resets at",
    signIn: "Sign in for 10 daily analyses",
    states: {
      idle: "Ready",
      queued: "Queued",
      downloading: "Downloading filing",
      parsing: "Parsing filing",
      analyzing: "Analyzing business",
      collecting: "Collecting official sources",
      extracting: "Extracting supply-chain entities",
      resolving: "Resolving company identities",
      verifying: "Verifying evidence",
      localizing: "Preparing languages",
      completed: "Analysis complete",
      failed: "Analysis failed",
      retrying: "Retrying",
    },
  },
  zh: {
    eyebrow: "研究 Agent",
    title: "生成带引用的公司研究",
    description: "下载最新 10-K，提取业务章节，核验结论，并生成中英文版本。",
    start: "运行 Agent 分析",
    retry: "重试分析",
    pending: "正在提交…",
    remaining: "次今日分析剩余",
    failed: "分析失败",
    limit: "今日额度已用完",
    reset: "重置时间",
    signIn: "登录后每天可分析 10 次",
    states: {
      idle: "准备就绪",
      queued: "已排队",
      downloading: "正在下载财报",
      parsing: "正在解析财报",
      analyzing: "正在分析业务",
      collecting: "正在收集官方资料",
      extracting: "正在提取产业链实体",
      resolving: "正在解析公司身份",
      verifying: "正在核验证据",
      localizing: "正在生成双语内容",
      completed: "分析完成",
      failed: "分析失败",
      retrying: "正在重试",
    },
  },
} as const;

export const companyPageCopy = {
  en: {
    loading: "Loading company research…",
    back: "Back to company search",
    notFoundTitle: "Company not found",
    notFoundDescription: "This US ticker is unavailable in the current SEC company universe.",
    primaryUnavailable: "Company data unavailable",
    unavailable: "Data unavailable",
    noIntelligence: "Run the research agent to build cited intelligence.",
    partialLoad: "Some secondary data could not be loaded. Available evidence remains visible.",
    header: {
      add: "Add to watchlist",
      remove: "Remove from watchlist",
      companyRecord: "Company record",
      sector: "Sector",
      industry: "Industry",
    },
    market: {
      eyebrow: "Market and valuation context",
      title: "Current snapshot",
      price: "Share price",
      marketCap: "Market cap",
      trailingEps: "Trailing EPS",
      trailingPe: "Trailing P/E",
      forwardPe: "Forward P/E",
      stale: "Stale market data",
      observed: "Market observed",
      provider: "Research-use quote via Yahoo",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "Four fiscal years plus TTM",
    },
    business: {
      eyebrow: "Business model",
      title: "Key businesses",
      empty: "Verified business claims are awaiting analysis.",
      revenue: "Revenue contribution",
      citation: "Citation",
    },
    evidence: {
      eyebrow: "Evidence Flow",
      title: "Where the company sits in its value chain",
      upstream: "Upstream",
      company: "Core business",
      downstream: "Downstream",
      partial: "Partial evidence coverage",
      insufficient: "The filing does not support a reliable value-chain map.",
      low: "Low confidence",
      citation: "Citation",
      sourceDialog: "Source evidence",
      openFiling: "Open SEC filing",
      viewFiling: "View source filing",
      close: "Close evidence",
    },
    graph: {
      eyebrow: "Agent-built market map",
      title: "AI supply-chain graph",
      thesis: "Research thesis",
      coverage: "Evidence coverage",
      generated: "Generated",
      layers: { upstream: "Upstream", core: "Core", downstream: "Downstream" },
      kinds: { company: "Company", business: "Business", product: "Product", category: "Category" },
      predicates: {
        supplies: "Supplies",
        sells_to: "Sells to",
        manufactures_for: "Manufactures for",
        depends_on: "Depends on",
        distributes_through: "Distributes through",
        competes_with: "Competes with",
      },
      verified: "Verified relationship",
      potential: "Potential relationship",
      potentialToggle: "Potential relationships",
      graphView: "Graph view",
      listView: "Relationship list",
      listLabel: "Supply-chain relationships",
      fit: "Fit graph",
      centerFocus: "Center focus company",
      confidence: "Confidence",
      verifiedNeighbors: "verified links",
      nodeDetails: "Entity profile",
      relationshipDetails: "Relationship evidence",
      description: "Description",
      identity: "Resolved identity",
      directRelationships: "Direct verified relationships",
      status: "Evidence status",
      observed: "Observed date",
      sources: "Official sources",
      excerpt: "Exact excerpt",
      locator: "Source location",
      openSource: "Open official source",
      close: "Close evidence",
      centerCompany: "Center on this company",
      generate: "Generate graph",
      refresh: "Refresh graph",
      retry: "Retry graph research",
      pending: "Submitting graph research…",
      refreshing: "A fresh Agent run is in progress. The current cited snapshot remains available.",
      failed: "Graph research request failed",
      limit: "Daily graph allowance used",
      remaining: "daily graph runs remaining",
      reset: "Resets at",
      emptyTitle: "Build this company’s cited market map",
      emptyDescription: "The Agent collects official materials, resolves companies, and verifies every displayed relationship.",
      insufficient: "Official evidence supports a limited graph",
      insufficientDescription: "The Agent completed its research and retained only relationships supported by the available official sources.",
      selectNode: "Select",
      stages: {
        queued: "Queued",
        downloading: "Downloading filings",
        parsing: "Parsing filings",
        analyzing: "Analyzing company context",
        collecting: "Collecting official sources",
        extracting: "Extracting entities and relationships",
        resolving: "Resolving company identities",
        verifying: "Verifying evidence",
        localizing: "Preparing languages",
        completed: "Graph complete",
        failed: "Graph research failed",
      },
    },
    insights: {
      dependencies: "Risks and material dependencies",
      competition: "Competition and open questions",
      quality: "Evidence quality",
      sources: "Source list",
      generated: "Intelligence generated",
      underlying: "Underlying filing",
      confidence: "Overall confidence",
    },
    analysis: analysisCopy.en,
  },
  zh: {
    loading: "正在载入公司研究…",
    back: "返回公司搜索",
    notFoundTitle: "未找到公司",
    notFoundDescription: "当前 SEC 公司范围中没有这个美股代码。",
    primaryUnavailable: "公司数据暂时不可用",
    unavailable: "数据暂时不可用",
    noIntelligence: "运行研究 Agent，生成带引用的公司研究。",
    partialLoad: "部分辅助数据载入失败，已保留可用信息和证据。",
    header: {
      add: "加入自选股",
      remove: "移出自选股",
      companyRecord: "公司档案",
      sector: "所属板块",
      industry: "所属行业",
    },
    market: {
      eyebrow: "行情与估值背景",
      title: "当前快照",
      price: "当前股价",
      marketCap: "总市值",
      trailingEps: "历史每股收益",
      trailingPe: "历史市盈率",
      forwardPe: "预期市盈率",
      stale: "行情数据已过期",
      observed: "行情时间",
      provider: "Yahoo 研究用途行情",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "最近四个财年与 TTM",
    },
    business: {
      eyebrow: "商业模式",
      title: "关键业务",
      empty: "等待 Agent 生成经过核验的业务结论。",
      revenue: "收入占比",
      citation: "引用",
    },
    evidence: {
      eyebrow: "证据流",
      title: "公司在产业链中的位置",
      upstream: "上游",
      company: "核心业务",
      downstream: "下游",
      partial: "证据覆盖不完整",
      insufficient: "财报证据不足以形成可靠的产业链图。",
      low: "低置信度",
      citation: "引用",
      sourceDialog: "原始证据",
      openFiling: "打开 SEC 财报",
      viewFiling: "查看原始财报",
      close: "关闭证据",
    },
    graph: {
      eyebrow: "Agent 生成的市场地图",
      title: "AI 产业链图谱",
      thesis: "研究结论",
      coverage: "证据覆盖",
      generated: "生成时间",
      layers: { upstream: "上游", core: "核心", downstream: "下游" },
      kinds: { company: "公司", business: "业务", product: "产品", category: "品类" },
      predicates: {
        supplies: "供应",
        sells_to: "销售给",
        manufactures_for: "为其制造",
        depends_on: "依赖",
        distributes_through: "通过其分销",
        competes_with: "竞争关系",
      },
      verified: "已核验关系",
      potential: "潜在线索",
      potentialToggle: "潜在线索",
      graphView: "图谱视图",
      listView: "关系列表",
      listLabel: "产业链关系",
      fit: "适应画布",
      centerFocus: "定位核心公司",
      confidence: "置信度",
      verifiedNeighbors: "条已核验关系",
      nodeDetails: "实体档案",
      relationshipDetails: "关系证据",
      description: "说明",
      identity: "公司身份",
      directRelationships: "直接核验关系",
      status: "证据状态",
      observed: "资料日期",
      sources: "官方来源",
      excerpt: "原文摘录",
      locator: "原文位置",
      openSource: "打开官方来源",
      close: "关闭证据",
      centerCompany: "以该公司为中心研究",
      generate: "生成图谱",
      refresh: "刷新图谱",
      retry: "重试图谱研究",
      pending: "正在提交图谱研究…",
      refreshing: "Agent 正在生成新版本，当前带引用的快照继续展示。",
      failed: "图谱研究请求失败",
      limit: "今日图谱额度已用完",
      remaining: "次今日图谱生成剩余",
      reset: "重置时间",
      emptyTitle: "生成该公司的带引用产业链地图",
      emptyDescription: "Agent 将收集官方资料、解析公司身份，并核验每一条展示关系。",
      insufficient: "官方证据仅支持有限图谱",
      insufficientDescription: "Agent 已完成研究，并仅保留现有官方资料能够支撑的关系。",
      selectNode: "选择",
      stages: {
        queued: "已排队",
        downloading: "正在下载财报",
        parsing: "正在解析财报",
        analyzing: "正在分析公司背景",
        collecting: "正在收集官方资料",
        extracting: "正在提取实体和关系",
        resolving: "正在解析公司身份",
        verifying: "正在核验证据",
        localizing: "正在生成双语内容",
        completed: "图谱已完成",
        failed: "图谱研究失败",
      },
    },
    insights: {
      dependencies: "风险与关键依赖",
      competition: "竞争与待研究问题",
      quality: "证据质量",
      sources: "来源列表",
      generated: "研究生成时间",
      underlying: "底层财报",
      confidence: "整体置信度",
    },
    analysis: analysisCopy.zh,
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends readonly (infer Item)[]
      ? Widen<Item>[]
      : T extends object
        ? { [Key in keyof T]: Widen<T[Key]> }
        : T;

export type CompanyPageCopy = Widen<(typeof companyPageCopy)["en"]>;
export type AnalysisCopy = Widen<(typeof analysisCopy)["en"]>;
