export const analysisCopy = {
  en: {
    eyebrow: "Research agent",
    title: "Build cited company intelligence",
    description: "Download the latest 10-K, extract its business sections, verify claims, and prepare both languages.",
    start: "Run agent analysis",
    retry: "Retry analysis",
    pending: "Submitting…",
    remaining: "daily analyses remaining",
    failed: "Analysis failed",
    limit: "Daily allowance used",
    reset: "Resets at",
    signIn: "Sign in for 10 daily analyses",
    states: {
      idle: "Ready",
      queued: "Queued",
      downloading: "Downloading filing",
      parsing: "Parsing filing",
      analyzing: "Analyzing business",
      verifying: "Verifying evidence",
      localizing: "Preparing languages",
      completed: "Analysis complete",
      failed: "Analysis failed",
      retrying: "Retrying",
    },
  },
  zh: {
    eyebrow: "研究 Agent",
    title: "生成带引用的公司研究",
    description: "下载最新 10-K，提取业务章节，核验结论，并生成中英文版本。",
    start: "运行 Agent 分析",
    retry: "重试分析",
    pending: "正在提交…",
    remaining: "次今日分析剩余",
    failed: "分析失败",
    limit: "今日额度已用完",
    reset: "重置时间",
    signIn: "登录后每天可分析 10 次",
    states: {
      idle: "准备就绪",
      queued: "已排队",
      downloading: "正在下载财报",
      parsing: "正在解析财报",
      analyzing: "正在分析业务",
      verifying: "正在核验证据",
      localizing: "正在生成双语内容",
      completed: "分析完成",
      failed: "分析失败",
      retrying: "正在重试",
    },
  },
} as const;

export const companyPageCopy = {
  en: {
    loading: "Loading company research…",
    back: "Back to company search",
    notFoundTitle: "Company not found",
    notFoundDescription: "This US ticker is unavailable in the current SEC company universe.",
    primaryUnavailable: "Company data unavailable",
    unavailable: "Data unavailable",
    noIntelligence: "Run the research agent to build cited intelligence.",
    partialLoad: "Some secondary data could not be loaded. Available evidence remains visible.",
    header: {
      add: "Add to watchlist",
      remove: "Remove from watchlist",
      companyRecord: "Company record",
      sector: "Sector",
      industry: "Industry",
    },
    market: {
      eyebrow: "Market and valuation context",
      title: "Current snapshot",
      price: "Share price",
      marketCap: "Market cap",
      trailingEps: "Trailing EPS",
      trailingPe: "Trailing P/E",
      forwardPe: "Forward P/E",
      stale: "Stale market data",
      observed: "Market observed",
      provider: "Research-use quote via Yahoo",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "Four fiscal years plus TTM",
    },
    business: {
      eyebrow: "Business model",
      title: "Key businesses",
      empty: "Verified business claims are awaiting analysis.",
      revenue: "Revenue contribution",
      citation: "Citation",
    },
    evidence: {
      eyebrow: "Evidence Flow",
      title: "Where the company sits in its value chain",
      upstream: "Upstream",
      company: "Core business",
      downstream: "Downstream",
      partial: "Partial evidence coverage",
      insufficient: "The filing does not support a reliable value-chain map.",
      low: "Low confidence",
      citation: "Citation",
      sourceDialog: "Source evidence",
      openFiling: "Open SEC filing",
      viewFiling: "View source filing",
      close: "Close evidence",
    },
    insights: {
      dependencies: "Risks and material dependencies",
      competition: "Competition and open questions",
      quality: "Evidence quality",
      sources: "Source list",
      generated: "Intelligence generated",
      underlying: "Underlying filing",
      confidence: "Overall confidence",
    },
    analysis: analysisCopy.en,
  },
  zh: {
    loading: "正在载入公司研究…",
    back: "返回公司搜索",
    notFoundTitle: "未找到公司",
    notFoundDescription: "当前 SEC 公司范围中没有这个美股代码。",
    primaryUnavailable: "公司数据暂时不可用",
    unavailable: "数据暂时不可用",
    noIntelligence: "运行研究 Agent，生成带引用的公司研究。",
    partialLoad: "部分辅助数据载入失败，已保留可用信息和证据。",
    header: {
      add: "加入自选股",
      remove: "移出自选股",
      companyRecord: "公司档案",
      sector: "所属板块",
      industry: "所属行业",
    },
    market: {
      eyebrow: "行情与估值背景",
      title: "当前快照",
      price: "当前股价",
      marketCap: "总市值",
      trailingEps: "历史每股收益",
      trailingPe: "历史市盈率",
      forwardPe: "预期市盈率",
      stale: "行情数据已过期",
      observed: "行情时间",
      provider: "Yahoo 研究用途行情",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "最近四个财年与 TTM",
    },
    business: {
      eyebrow: "商业模式",
      title: "关键业务",
      empty: "等待 Agent 生成经过核验的业务结论。",
      revenue: "收入占比",
      citation: "引用",
    },
    evidence: {
      eyebrow: "证据流",
      title: "公司在产业链中的位置",
      upstream: "上游",
      company: "核心业务",
      downstream: "下游",
      partial: "证据覆盖不完整",
      insufficient: "财报证据不足以形成可靠的产业链图。",
      low: "低置信度",
      citation: "引用",
      sourceDialog: "原始证据",
      openFiling: "打开 SEC 财报",
      viewFiling: "查看原始财报",
      close: "关闭证据",
    },
    insights: {
      dependencies: "风险与关键依赖",
      competition: "竞争与待研究问题",
      quality: "证据质量",
      sources: "来源列表",
      generated: "研究生成时间",
      underlying: "底层财报",
      confidence: "整体置信度",
    },
    analysis: analysisCopy.zh,
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends readonly (infer Item)[]
      ? Widen<Item>[]
      : T extends object
        ? { [Key in keyof T]: Widen<T[Key]> }
        : T;

export type CompanyPageCopy = Widen<(typeof companyPageCopy)["en"]>;
export type AnalysisCopy = Widen<(typeof analysisCopy)["en"]>;
