export const analysisCopy = {
  en: {
    eyebrow: "Research agent",
    title: "Build cited company intelligence",
    description: "Download the latest 10-K, extract its business sections, verify claims, and prepare both languages.",
    start: "Run agent analysis",
    retry: "Retry analysis",
    pending: "Submitting…",
    remaining: "daily analyses remaining",
    failed: "Analysis failed",
    limit: "Daily allowance used",
    reset: "Resets at",
    signIn: "Sign in for 10 daily analyses",
    states: {
      idle: "Ready",
      queued: "Queued",
      downloading: "Downloading filing",
      parsing: "Parsing filing",
      analyzing: "Analyzing business",
      collecting: "Collecting official sources",
      extracting: "Extracting supply-chain entities",
      resolving: "Resolving company identities",
      verifying: "Verifying evidence",
      localizing: "Preparing languages",
      completed: "Analysis complete",
      failed: "Analysis failed",
      retrying: "Retrying",
    },
  },
  zh: {
    eyebrow: "研究 Agent",
    title: "生成带引用的公司研究",
    description: "下载最新 10-K，提取业务章节，核验结论，并生成中英文版本。",
    start: "运行 Agent 分析",
    retry: "重试分析",
    pending: "正在提交…",
    remaining: "次今日分析剩余",
    failed: "分析失败",
    limit: "今日额度已用完",
    reset: "重置时间",
    signIn: "登录后每天可分析 10 次",
    states: {
      idle: "准备就绪",
      queued: "已排队",
      downloading: "正在下载财报",
      parsing: "正在解析财报",
      analyzing: "正在分析业务",
      collecting: "正在收集官方资料",
      extracting: "正在提取产业链实体",
      resolving: "正在解析公司身份",
      verifying: "正在核验证据",
      localizing: "正在生成双语内容",
      completed: "分析完成",
      failed: "分析失败",
      retrying: "正在重试",
    },
  },
} as const;

export const companyPageCopy = {
  en: {
    loading: "Loading company research…",
    back: "Back to company search",
    notFoundTitle: "Company not found",
    notFoundDescription: "This US ticker is unavailable in the current SEC company universe.",
    primaryUnavailable: "Company data unavailable",
    unavailable: "Data unavailable",
    noIntelligence: "Run the research agent to build cited intelligence.",
    partialLoad: "Some secondary data could not be loaded. Available evidence remains visible.",
    header: {
      add: "Add to watchlist",
      remove: "Remove from watchlist",
      ask: "Ask EquityLens",
      companyRecord: "Company record",
      sector: "Sector",
      industry: "Industry",
    },
    chat: {
      eyebrow: "Company research Agent",
      title: "Ask EquityLens",
      question: "Research question",
      placeholder: "Ask about the business, valuation, filings, or supply chain…",
      send: "Send question",
      close: "Close research chat",
      history: "Conversation history",
      hideHistory: "Hide conversation history",
      newConversation: "New conversation",
      startFresh: "Archive and start fresh",
      rename: "Rename conversation",
      archive: "Archive conversation",
      conversationTitle: "Conversation title",
      saveTitle: "Save title",
      cancel: "Cancel",
      loadMore: "Load more messages",
      retry: "Retry answer",
      webAutomatic: "Web evidence is selected automatically when current context is required.",
      empty: "Ask a focused question to begin an evidence-backed company research thread.",
      guestHistory: "This temporary conversation is retained for seven days.",
      userHistory: "Saved company conversations",
      selectedContext: "Selected page context",
      removeContext: "Remove context",
      clearContext: "Clear context",
      quotaRemaining: "message remaining",
      quotaRemainingPlural: "messages remaining",
      quotaReset: "Resets",
      quotaUnavailable: "Chat allowance unavailable",
      quotaUsed: "Daily chat allowance used",
      disclaimer: "Research support only. Verify primary sources before making investment decisions.",
      sending: "Agent is researching…",
      sources: "Cited sources",
      sourceTier: "Source tier",
      published: "Published",
      retrieved: "Retrieved",
      sourceLocation: "Source location",
      excerpt: "Evidence excerpt",
      openSource: "Open source",
      evidenceCoverage: "Evidence coverage",
      errors: {
        load: "Research chat could not be loaded.",
        stream: "The answer stream was interrupted.",
        quota: "Today’s chat allowance has been used.",
        generic: "The research Agent could not complete this answer.",
      },
      stages: {
        retrieval: "Retrieving company evidence",
        web: "Checking current web evidence",
        compose: "Composing cited answer",
        verify: "Verifying claims and sources",
      },
      sections: {
        directConclusion: "Direct conclusion",
        keyEvidence: "Key evidence",
        risksAndUncertainties: "Risks and uncertainties",
        sources: "Sources",
      },
      suggestedLabel: "Suggested questions",
      suggestedQuestions: [
        "What are this company’s key businesses and revenue drivers?",
        "Where does this company sit in its supply chain?",
        "What do its current valuation multiples imply?",
      ],
      readiness: {
        title: "Evidence readiness",
        zeroQuota: "Filing preparation uses zero chat or Agent quota.",
        prepareIndex: "Prepare 10-K for chat",
        startAnalysis: "Start company analysis",
        generateGraph: "Generate supply-chain graph",
        resources: {
          intelligence: "Structured intelligence",
          filingText: "Latest 10-K text",
          filingIndex: "10-K search index",
          graph: "Supply-chain graph",
          web: "Current web evidence",
        },
        states: {
          ready: "Ready",
          missing: "Missing",
          running: "In progress",
          failed: "Action required",
        },
      },
    },
    market: {
      eyebrow: "Market and valuation context",
      title: "Current snapshot",
      ask: "Ask EquityLens",
      price: "Share price",
      marketCap: "Market cap",
      trailingEps: "Trailing EPS",
      trailingPe: "Trailing P/E",
      forwardPe: "Forward P/E",
      stale: "Stale market data",
      observed: "Market observed",
      provider: "Research-use quote via Yahoo",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "Four fiscal years plus TTM",
      ask: "Ask EquityLens",
    },
    business: {
      eyebrow: "Business model",
      title: "Key businesses",
      ask: "Ask EquityLens",
      empty: "Verified business claims are awaiting analysis.",
      revenue: "Revenue contribution",
      citation: "Citation",
    },
    evidence: {
      eyebrow: "Evidence Flow",
      title: "Where the company sits in its value chain",
      upstream: "Upstream",
      company: "Core business",
      downstream: "Downstream",
      partial: "Partial evidence coverage",
      insufficient: "The filing does not support a reliable value-chain map.",
      low: "Low confidence",
      citation: "Citation",
      sourceDialog: "Source evidence",
      openFiling: "Open SEC filing",
      viewFiling: "View source filing",
      close: "Close evidence",
    },
    graph: {
      eyebrow: "Agent-built market map",
      title: "AI supply-chain graph",
      thesis: "Research thesis",
      coverage: "Evidence coverage",
      generated: "Generated",
      layers: { upstream: "Upstream", core: "Core", downstream: "Downstream" },
      kinds: { company: "Company", business: "Business", product: "Product", category: "Category" },
      predicates: {
        supplies: "Supplies",
        sells_to: "Sells to",
        manufactures_for: "Manufactures for",
        depends_on: "Depends on",
        distributes_through: "Distributes through",
        competes_with: "Competes with",
      },
      verified: "Verified relationship",
      potential: "Potential relationship",
      potentialToggle: "Potential relationships",
      graphView: "Graph view",
      listView: "Relationship list",
      listLabel: "Supply-chain relationships",
      fit: "Fit graph",
      centerFocus: "Center focus company",
      confidence: "Confidence",
      verifiedNeighbors: "verified links",
      nodeDetails: "Entity profile",
      relationshipDetails: "Relationship evidence",
      description: "Description",
      identity: "Resolved identity",
      directRelationships: "Direct verified relationships",
      status: "Evidence status",
      observed: "Observed date",
      sources: "Official sources",
      excerpt: "Exact excerpt",
      locator: "Source location",
      openSource: "Open official source",
      close: "Close evidence",
      centerCompany: "Center on this company",
      generate: "Generate graph",
      refresh: "Refresh graph",
      retry: "Retry graph research",
      pending: "Submitting graph research…",
      refreshing: "A fresh Agent run is in progress. The current cited snapshot remains available.",
      failed: "Graph research request failed",
      limit: "Daily graph allowance used",
      remaining: "daily graph runs remaining",
      reset: "Resets at",
      emptyTitle: "Build this company’s cited market map",
      emptyDescription: "The Agent collects official materials, resolves companies, and verifies every displayed relationship.",
      insufficient: "Official evidence supports a limited graph",
      insufficientDescription: "The Agent completed its research and retained only relationships supported by the available official sources.",
      selectNode: "Select",
      askNode: "Ask EquityLens",
      askRelationship: "Ask EquityLens about this relationship",
      stages: {
        queued: "Queued",
        downloading: "Downloading filings",
        parsing: "Parsing filings",
        analyzing: "Analyzing company context",
        collecting: "Collecting official sources",
        extracting: "Extracting entities and relationships",
        resolving: "Resolving company identities",
        verifying: "Verifying evidence",
        localizing: "Preparing languages",
        completed: "Graph complete",
        failed: "Graph research failed",
      },
    },
    insights: {
      dependencies: "Risks and material dependencies",
      competition: "Competition and open questions",
      quality: "Evidence quality",
      sources: "Source list",
      generated: "Intelligence generated",
      underlying: "Underlying filing",
      confidence: "Overall confidence",
    },
    analysis: analysisCopy.en,
  },
  zh: {
    loading: "正在载入公司研究…",
    back: "返回公司搜索",
    notFoundTitle: "未找到公司",
    notFoundDescription: "当前 SEC 公司范围中没有这个美股代码。",
    primaryUnavailable: "公司数据暂时不可用",
    unavailable: "数据暂时不可用",
    noIntelligence: "运行研究 Agent，生成带引用的公司研究。",
    partialLoad: "部分辅助数据载入失败，已保留可用信息和证据。",
    header: {
      add: "加入自选股",
      remove: "移出自选股",
      ask: "询问 EquityLens",
      companyRecord: "公司档案",
      sector: "所属板块",
      industry: "所属行业",
    },
    chat: {
      eyebrow: "公司投研 Agent",
      title: "询问 EquityLens",
      question: "投研问题",
      placeholder: "询问业务、估值、财报或产业链问题…",
      send: "发送问题",
      close: "关闭投研对话",
      history: "对话历史",
      hideHistory: "收起对话历史",
      newConversation: "新建对话",
      startFresh: "归档并开始新对话",
      rename: "重命名对话",
      archive: "归档对话",
      conversationTitle: "对话标题",
      saveTitle: "保存标题",
      cancel: "取消",
      loadMore: "加载更多消息",
      retry: "重试回答",
      webAutomatic: "需要最新背景时，Agent 会自动选择网页证据。",
      empty: "提出一个聚焦问题，开始有证据支撑的公司投研对话。",
      guestHistory: "该临时对话将保留七天。",
      userHistory: "已保存的公司对话",
      selectedContext: "已选择的页面上下文",
      removeContext: "移除上下文",
      clearContext: "清空上下文",
      quotaRemaining: "次对话剩余",
      quotaRemainingPlural: "次对话剩余",
      quotaReset: "重置时间",
      quotaUnavailable: "对话额度暂不可用",
      quotaUsed: "今日对话额度已用完",
      disclaimer: "内容仅供研究参考。投资决策前请核验一手来源。",
      sending: "Agent 正在研究…",
      sources: "引用来源",
      sourceTier: "来源等级",
      published: "发布时间",
      retrieved: "检索时间",
      sourceLocation: "来源位置",
      excerpt: "证据摘录",
      openSource: "打开来源",
      evidenceCoverage: "证据覆盖",
      errors: {
        load: "投研对话加载失败。",
        stream: "回答流已中断。",
        quota: "今日对话额度已用完。",
        generic: "研究 Agent 未能完成该回答。",
      },
      stages: {
        retrieval: "正在检索公司证据",
        web: "正在核查最新网页证据",
        compose: "正在生成带引用回答",
        verify: "正在核验结论与来源",
      },
      sections: {
        directConclusion: "直接结论",
        keyEvidence: "关键证据",
        risksAndUncertainties: "风险与不确定性",
        sources: "来源",
      },
      suggestedLabel: "建议问题",
      suggestedQuestions: [
        "这家公司的关键业务和收入驱动因素是什么？",
        "这家公司位于产业链的哪个位置？",
        "当前估值倍数反映了什么预期？",
      ],
      readiness: {
        title: "证据准备状态",
        zeroQuota: "财报索引准备不消耗对话或 Agent 额度。",
        prepareIndex: "为对话准备 10-K",
        startAnalysis: "开始公司分析",
        generateGraph: "生成产业链图谱",
        resources: {
          intelligence: "结构化公司研究",
          filingText: "最新 10-K 正文",
          filingIndex: "10-K 检索索引",
          graph: "产业链图谱",
          web: "最新网页证据",
        },
        states: {
          ready: "已就绪",
          missing: "待准备",
          running: "进行中",
          failed: "需要处理",
        },
      },
    },
    market: {
      eyebrow: "行情与估值背景",
      title: "当前快照",
      ask: "询问 EquityLens",
      price: "当前股价",
      marketCap: "总市值",
      trailingEps: "历史每股收益",
      trailingPe: "历史市盈率",
      forwardPe: "预期市盈率",
      stale: "行情数据已过期",
      observed: "行情时间",
      provider: "Yahoo 研究用途行情",
    },
    financials: {
      eyebrow: "SEC Company Facts",
      title: "最近四个财年与 TTM",
      ask: "询问 EquityLens",
    },
    business: {
      eyebrow: "商业模式",
      title: "关键业务",
      ask: "询问 EquityLens",
      empty: "等待 Agent 生成经过核验的业务结论。",
      revenue: "收入占比",
      citation: "引用",
    },
    evidence: {
      eyebrow: "证据流",
      title: "公司在产业链中的位置",
      upstream: "上游",
      company: "核心业务",
      downstream: "下游",
      partial: "证据覆盖不完整",
      insufficient: "财报证据不足以形成可靠的产业链图。",
      low: "低置信度",
      citation: "引用",
      sourceDialog: "原始证据",
      openFiling: "打开 SEC 财报",
      viewFiling: "查看原始财报",
      close: "关闭证据",
    },
    graph: {
      eyebrow: "Agent 生成的市场地图",
      title: "AI 产业链图谱",
      thesis: "研究结论",
      coverage: "证据覆盖",
      generated: "生成时间",
      layers: { upstream: "上游", core: "核心", downstream: "下游" },
      kinds: { company: "公司", business: "业务", product: "产品", category: "品类" },
      predicates: {
        supplies: "供应",
        sells_to: "销售给",
        manufactures_for: "为其制造",
        depends_on: "依赖",
        distributes_through: "通过其分销",
        competes_with: "竞争关系",
      },
      verified: "已核验关系",
      potential: "潜在线索",
      potentialToggle: "潜在线索",
      graphView: "图谱视图",
      listView: "关系列表",
      listLabel: "产业链关系",
      fit: "适应画布",
      centerFocus: "定位核心公司",
      confidence: "置信度",
      verifiedNeighbors: "条已核验关系",
      nodeDetails: "实体档案",
      relationshipDetails: "关系证据",
      description: "说明",
      identity: "公司身份",
      directRelationships: "直接核验关系",
      status: "证据状态",
      observed: "资料日期",
      sources: "官方来源",
      excerpt: "原文摘录",
      locator: "原文位置",
      openSource: "打开官方来源",
      close: "关闭证据",
      centerCompany: "以该公司为中心研究",
      generate: "生成图谱",
      refresh: "刷新图谱",
      retry: "重试图谱研究",
      pending: "正在提交图谱研究…",
      refreshing: "Agent 正在生成新版本，当前带引用的快照继续展示。",
      failed: "图谱研究请求失败",
      limit: "今日图谱额度已用完",
      remaining: "次今日图谱生成剩余",
      reset: "重置时间",
      emptyTitle: "生成该公司的带引用产业链地图",
      emptyDescription: "Agent 将收集官方资料、解析公司身份，并核验每一条展示关系。",
      insufficient: "官方证据仅支持有限图谱",
      insufficientDescription: "Agent 已完成研究，并仅保留现有官方资料能够支撑的关系。",
      selectNode: "选择",
      askNode: "询问 EquityLens",
      askRelationship: "向 EquityLens 询问该关系",
      stages: {
        queued: "已排队",
        downloading: "正在下载财报",
        parsing: "正在解析财报",
        analyzing: "正在分析公司背景",
        collecting: "正在收集官方资料",
        extracting: "正在提取实体和关系",
        resolving: "正在解析公司身份",
        verifying: "正在核验证据",
        localizing: "正在生成双语内容",
        completed: "图谱已完成",
        failed: "图谱研究失败",
      },
    },
    insights: {
      dependencies: "风险与关键依赖",
      competition: "竞争与待研究问题",
      quality: "证据质量",
      sources: "来源列表",
      generated: "研究生成时间",
      underlying: "底层财报",
      confidence: "整体置信度",
    },
    analysis: analysisCopy.zh,
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends readonly (infer Item)[]
      ? readonly Widen<Item>[]
      : T extends object
        ? { [Key in keyof T]: Widen<T[Key]> }
        : T;

export type CompanyPageCopy = Widen<(typeof companyPageCopy)["en"]>;
export type AnalysisCopy = Widen<(typeof analysisCopy)["en"]>;
export type CompanyChatCopy = CompanyPageCopy["chat"];
